SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

TRIANGLE_WIDTH = SCREEN_WIDTH // 15
TRIANGLE_HEIGHT = int(SCREEN_HEIGHT * 0.4)
BOARD_HEIGHT = 20
BOARD_WIDTH = TRIANGLE_WIDTH
OFF_SECTION_WIDTH = BOARD_WIDTH - 2 * BOARD_HEIGHT
OFF_SECTION_ADDED_HEIGHT = 20
OFF_SECTION_HEIGHT = TRIANGLE_HEIGHT + OFF_SECTION_ADDED_HEIGHT

PIECE_RADIUS = TRIANGLE_HEIGHT // 10
TAKEN_PIECE_WIDTH = OFF_SECTION_WIDTH
TAKEN_PIECE_HEIGHT = OFF_SECTION_HEIGHT // 15